### ISSUE TITLE
Submarine editor crashes when using wiring mode.

### ISSUE THREAD

**Issue by Momiro** [NilanthAnimosus/Barotrauma---Nilanths-Edits#4]
Crashreport.txt

Barotrauma Client crash report (generated on 8/3/2018 6:41:23 PM)

Barotrauma seems to have crashed. Sorry for the inconvenience! 

Game version 0.8.1.10 NILMOD SERVER MODIFICATION
Nilmod version stamp: 30/07/2018-1
Graphics mode: 1920x1200 (BorderlessWindowed)
Selected content package: Vanilla 0.8
Level seed: no level loaded
Loaded submarine: SS Smol MK II (836A662C20760EE336E5CEB1E418384A)
Selected screen: Barotrauma.SubEditorScreen

System info:
    Operating system: Microsoft Windows NT 6.2.9200.0 64 bit
    GPU name: NVIDIA GeForce GTX 970
    Display mode: {Width:1920 Height:1200 Format:Color AspectRatio:1.6}
    GPU status: Normal

This was running NilMod Code!

Exception: Object reference not set to an instance of an object.
Target site: Boolean get_AllowInput()
Stack trace: 
   at Barotrauma.Character.get_AllowInput() in F:\Barotrauma\BT NilEdit\Barotrauma---Nilanths-Edits\Barotrauma\BarotraumaShared\Source\Characters\Character.cs:line 660
   at Barotrauma.Character.get_CanInteract() in F:\Barotrauma\BT NilEdit\Barotrauma---Nilanths-Edits\Barotrauma\BarotraumaShared\Source\Characters\Character.cs:line 671
   at Barotrauma.Character.DoInteractionUpdate(Single deltaTime, Vector2 mouseSimPos) in F:\Barotrauma\BT NilEdit\Barotrauma---Nilanths-Edits\Barotrauma\BarotraumaShared\Source\Characters\Character.cs:line 2224
   at Barotrauma.Character.ControlLocalPlayer(Single deltaTime, Camera cam, Boolean moveCam) in F:\Barotrauma\BT NilEdit\Barotrauma---Nilanths-Edits\Barotrauma\BarotraumaClient\Source\Characters\Character.cs:line 382
   at Barotrauma.SubEditorScreen.Update(Double deltaTime) in F:\Barotrauma\BT NilEdit\Barotrauma---Nilanths-Edits\Barotrauma\BarotraumaClient\Source\Screens\SubEditorScreen.cs:line 1431
   at Barotrauma.GameMain.Update(GameTime gameTime) in F:\Barotrauma\BT NilEdit\Barotrauma---Nilanths-Edits\Barotrauma\BarotraumaClient\Source\GameMain.cs:line 685
   at Microsoft.Xna.Framework.Game.DoUpdate(GameTime gameTime)
   at Microsoft.Xna.Framework.Game.Tick()
   at MonoGame.Framework.WinFormsGameWindow.RunLoop()
   at MonoGame.Framework.WinFormsGamePlatform.RunLoop()
   at Microsoft.Xna.Framework.Game.Run(GameRunBehavior runBehavior)
   at Barotrauma.Program.Main() in F:\Barotrauma\BT NilEdit\Barotrauma---Nilanths-Edits\Barotrauma\BarotraumaClient\Source\Program.cs:line 48

Last debug messages:
[8/3/2018 6:41:06 PM] Enter "help" for a list of available console commands

**Comment by NilanthAnimosus** [comment]
Fixed for the next update.
